// main.cpp
#include "Lexer.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <stdexcept>

std::string readFileToString(const std::string &filename) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("Could not open file: " + filename);
    }

    std::stringstream buffer;
    buffer << file.rdbuf(); // read the whole file into the buffer
    return buffer.str();
}


int main(int argc, char *argv[]) {

  if (argc < 2) {
    std::cout << "Need filepath." << std::endl;
    return 1;
  }

  std::string sourceCodeFilepath = argv[1];

  std::string sourceCode = readFileToString(sourceCodeFilepath);
  Lexer lexer(sourceCode);
  std::vector<Token> tokens = lexer.tokenize();

  std::cout << "Source code: " << sourceCode << std::endl << std::endl;
  std::cout << "Tokens Generated by Lexical Analyzer:" << std::endl;
  printTokens(tokens);

  return 0;
}
